import "../css/global.css";
import Head from "next/head";
import Layout from "@components/layout";

function MyApp({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>Emanuele Vella's portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Abel&family=Antonio&family=Open+Sans&family=Oswald:wght@600&display=swap" rel="stylesheet"/>
      </Head>
      <Component {...pageProps} />
    </Layout>
  );
}

export default MyApp;
