import Head from 'next/head'
import styled from 'styled-components'
import GlobalStyle from '../utils/style/globalStyle'
import { Row, Column } from '../utils/style/style'
import Image from 'next/image'


const Body = styled.div`
  height: 100%;
  width: 100%;
  position: absolute;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Title = styled.span`
  font-family: 'Abel', sans-serif;
  color: #111;
  font-weight: 500;
  font-size: 2rem;
  -webkit-font-smoothing: antialiased;
  -webkit-text-size-adjust: 100%;
  margin-bottom: 3rem;
  opacity: 0.7;
  -webkit-text-stroke: 1px #111;
`

const TitleHighlight = styled.span`
  font-family: 'Abel', sans-serif;
  color: green;
  -webkit-text-stroke: 1px green;
  font-weight: 700;
  font-size: 2rem;
  -webkit-font-smoothing: antialiased;
  -webkit-text-size-adjust: 100%;
  opacity: 0.7;
`

const Sections = styled.div`
  margin-left: 30px;
  font-family: 'Oswald', sans-serif;
  color: white;
  font-size: 5rem;
  -webkit-text-stroke: 1px #111;
  background: linear-gradient(to right, orange, orange 50%, transparent 50%);
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-size: 200% 100%;
  background-position: 100%;
  opacity: 0.7;
  -webkit-font-smoothing: antialiased;
  -webkit-text-size-adjust: 100%;
  transition: background-position 1000ms ease;
  &:hover{
    cursor: pointer;
    background-position: 0 100%;
  }
`

const SectionMiddle = styled.div`
  margin-left: 30px;
  font-family: 'Oswald', sans-serif;
  color: white;
  font-size: 5rem;
  -webkit-text-stroke: 1px #111;
  background: linear-gradient(to right, red, red 50%, #111 50%);
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-size: 200% 100%;
  background-position: 100%;
  opacity: 0.7;
  -webkit-font-smoothing: antialiased;
  -webkit-text-size-adjust: 100%;
  transition: background-position 1000ms ease;
  &:hover{
    cursor: pointer;
    background-position: 0 100%;
  }
`

const PhotoWrapper = styled.div`
  display: inline-block;
  position: relative;
  width: 350px;
  height: 350px;
  overflow: hidden;
  border-radius: 50%;
  filter: grayscale(1);
  transition: filter 1000ms ease;
  &:hover{
    cursor: pointer;
    background-position: 0 100%;
    filter: grayscale(0);
  }
`


export default function Home() {
  return (
    <Body>
      <Head>
        <title>Emanuele Vella's portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Abel&family=Antonio&family=Open+Sans&family=Oswald:wght@600&display=swap" rel="stylesheet"/>
      </Head>

      <GlobalStyle/>
      <div className="background"/>
      <Title>Hi, I'm Emanuele, and I'm a <TitleHighlight>Full-Stack Developer.</TitleHighlight></Title>
        <Column>
        <Row>
            <Sections className="greyscale">ABOUT-ME</Sections>
            <SectionMiddle>WORKS</SectionMiddle>
            <Sections>CONTACT-ME</Sections>
        </Row>
        <PhotoWrapper>
          <Image
            src="/photo.jpg"
            alt="Picture of the author"
            layout="responsive"
            height={800}
            width={450}
          />
        </PhotoWrapper>
        </Column>
        
      <footer>
      </footer>
    </Body>
  )
}
